/**
 * Dados mockados para desenvolvimento da interface antes da conexão real
 * com o Supabase. Cobrem os principais cenários de cada área prioritária.
 */
import type {
  AppNotification,
  Appointment,
  FollowUp,
  Lead,
  LegalDocument,
  Task,
  TeamUser,
  TimelineEntry,
} from "./types";

export const mockTeam: TeamUser[] = [
  {
    id: "u1",
    name: "Dr. Jean Braz",
    email: "jean@escritoriobraz.adv.br",
    role: "admin",
    active: true,
    last_login: "2026-05-30T09:12:00Z",
    created_at: "2025-01-10T12:00:00Z",
  },
  {
    id: "u2",
    name: "Marina Alves",
    email: "marina@escritoriobraz.adv.br",
    role: "advogado",
    active: true,
    last_login: "2026-05-29T18:40:00Z",
    created_at: "2025-02-01T12:00:00Z",
  },
  {
    id: "u3",
    name: "Rafael Costa",
    email: "rafael@escritoriobraz.adv.br",
    role: "atendente",
    active: true,
    last_login: "2026-05-30T08:05:00Z",
    created_at: "2025-03-15T12:00:00Z",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    full_name: "Carlos Henrique Souza",
    phone: "(11) 98877-1234",
    email: "carlos.souza@email.com",
    city: "São Paulo",
    state: "SP",
    legal_area: "penal",
    subarea: "Prisão em flagrante",
    case_type: "Defesa criminal — flagrante",
    case_summary:
      "Familiar relata prisão em flagrante ocorrida na madrugada. Audiência de custódia marcada. Solicita atuação urgente.",
    urgency: "alta",
    urgency_reason: "Prisão em flagrante com audiência de custódia em menos de 24h",
    commercial_status: "novo_lead",
    legal_status: "triagem_inicial",
    financial_status: "consulta_pendente",
    source: "chatbot",
    assigned_to: "u1",
    consent_given: true,
    consent_at: "2026-05-30T03:20:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: false,
    preferred_contact_time: "Imediato",
    next_action: "Contato imediato — audiência de custódia",
    created_at: "2026-05-30T03:18:00Z",
    updated_at: "2026-05-30T03:25:00Z",
  },
  {
    id: "lead-002",
    full_name: "Fernanda Lima",
    phone: "(11) 99654-7788",
    email: "fernanda.lima@email.com",
    city: "Guarulhos",
    state: "SP",
    legal_area: "civil",
    subarea: "Indenização contratual",
    case_type: "Descumprimento de contrato de prestação de serviços",
    case_summary:
      "Empresa contratada não entregou o serviço e se recusa a devolver os valores pagos. Há contrato assinado e comprovantes.",
    urgency: "media",
    urgency_reason: "Prejuízo financeiro relevante, sem prazo judicial imediato",
    commercial_status: "em_qualificacao",
    legal_status: "analise_documental",
    financial_status: "consulta_pendente",
    source: "site",
    assigned_to: "u2",
    consent_given: true,
    consent_at: "2026-05-28T14:10:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: false,
    preferred_contact_time: "Tarde",
    next_action: "Solicitar contrato e comprovantes",
    created_at: "2026-05-28T14:05:00Z",
    updated_at: "2026-05-29T10:30:00Z",
  },
  {
    id: "lead-003",
    full_name: "José Pereira da Silva",
    phone: "(11) 97766-5544",
    email: "jose.pereira@email.com",
    city: "Osasco",
    state: "SP",
    legal_area: "administrativo",
    subarea: "PAD — servidor público",
    case_type: "Defesa em processo administrativo disciplinar",
    case_summary:
      "Servidor recebeu notificação de instauração de PAD com prazo de defesa em 10 dias. Possui cópia da portaria.",
    urgency: "alta",
    urgency_reason: "Prazo de defesa administrativa próximo (10 dias)",
    commercial_status: "consulta_agendada",
    legal_status: "estrategia_em_definicao",
    financial_status: "honorarios_pendentes",
    source: "indicacao",
    assigned_to: "u2",
    consent_given: true,
    consent_at: "2026-05-27T09:00:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: true,
    is_existing_client: false,
    preferred_contact_time: "Manhã",
    next_action: "Reunião de estratégia — quinta-feira",
    created_at: "2026-05-27T08:50:00Z",
    updated_at: "2026-05-29T16:00:00Z",
  },
  {
    id: "lead-004",
    full_name: "Maria Aparecida Gomes",
    phone: "(11) 96655-3322",
    email: "maria.gomes@email.com",
    city: "São Paulo",
    state: "SP",
    legal_area: "previdenciario",
    subarea: "Auxílio-doença negado",
    case_type: "Recurso administrativo / ação previdenciária",
    case_summary:
      "Benefício de auxílio-doença negado pelo INSS. Possui carta de indeferimento e laudos médicos. Aguardando envio do CNIS.",
    urgency: "media",
    urgency_reason: "Negativa recente, prazo de recurso a confirmar",
    commercial_status: "aguardando_documentos",
    legal_status: "analise_documental",
    financial_status: "sem_cobranca",
    source: "instagram",
    assigned_to: "u2",
    consent_given: true,
    consent_at: "2026-05-26T11:20:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: false,
    preferred_contact_time: "Tarde",
    next_action: "Aguardando CNIS e carteira de trabalho",
    created_at: "2026-05-26T11:15:00Z",
    updated_at: "2026-05-28T09:00:00Z",
  },
  {
    id: "lead-005",
    full_name: "Roberto Carlos Menezes",
    phone: "(11) 95544-2211",
    email: "roberto.menezes@email.com",
    city: "Santo André",
    state: "SP",
    legal_area: "bancario",
    subarea: "Busca e apreensão de veículo",
    case_type: "Defesa em ação de busca e apreensão",
    case_summary:
      "Cliente foi citado em ação de busca e apreensão de veículo financiado. Alega cobrança de juros abusivos. Há contrato e extratos.",
    urgency: "alta",
    urgency_reason: "Ação de busca e apreensão com risco de perda do veículo",
    commercial_status: "negociacao",
    legal_status: "aguardando_contrato",
    financial_status: "entrada_paga",
    source: "google",
    assigned_to: "u1",
    consent_given: true,
    consent_at: "2026-05-25T15:40:00Z",
    privacy_policy_version: "1.0.0",
    process_number: "1002345-67.2026.8.26.0554",
    has_existing_process: true,
    is_existing_client: false,
    preferred_contact_time: "Noite",
    next_action: "Enviar contrato de honorários",
    created_at: "2026-05-25T15:35:00Z",
    updated_at: "2026-05-29T19:10:00Z",
  },
  {
    id: "lead-006",
    full_name: "Ana Beatriz Rocha",
    phone: "(11) 94433-1100",
    email: "ana.rocha@email.com",
    city: "São Bernardo do Campo",
    state: "SP",
    legal_area: "imobiliario",
    subarea: "Usucapião",
    case_type: "Regularização de imóvel sem matrícula",
    case_summary:
      "Família ocupa imóvel há mais de 15 anos sem registro. Deseja regularizar. Possui contas em nome próprio e contrato de gaveta.",
    urgency: "baixa",
    urgency_reason: "Sem prazo definido — regularização preventiva",
    commercial_status: "aguardando_documentos",
    legal_status: "triagem_inicial",
    financial_status: "sem_cobranca",
    source: "indicacao",
    assigned_to: null,
    consent_given: true,
    consent_at: "2026-05-24T10:00:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: false,
    preferred_contact_time: "Manhã",
    next_action: "Solicitar matrícula e comprovantes de posse",
    created_at: "2026-05-24T09:55:00Z",
    updated_at: "2026-05-24T10:05:00Z",
  },
  {
    id: "lead-007",
    full_name: "Distribuidora Nova Era LTDA",
    phone: "(11) 3322-1100",
    email: "contato@novaera.com.br",
    city: "São Paulo",
    state: "SP",
    legal_area: "lgpd",
    subarea: "Adequação LGPD",
    case_type: "Compliance e adequação à LGPD",
    case_summary:
      "Empresa de médio porte deseja adequar processos à LGPD. Coleta dados de clientes via site e CRM. Não possui política de privacidade.",
    urgency: "baixa",
    urgency_reason: "Demanda preventiva, sem incidente",
    commercial_status: "proposta_enviada",
    legal_status: "estrategia_em_definicao",
    financial_status: "consulta_pendente",
    source: "site",
    assigned_to: "u2",
    consent_given: true,
    consent_at: "2026-05-22T13:30:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: false,
    preferred_contact_time: "Comercial",
    next_action: "Follow-up da proposta enviada",
    created_at: "2026-05-22T13:25:00Z",
    updated_at: "2026-05-27T11:00:00Z",
  },
  {
    id: "lead-008",
    full_name: "Paulo Ricardo Tavares",
    phone: "(11) 93322-9988",
    email: "paulo.tavares@email.com",
    city: "Diadema",
    state: "SP",
    legal_area: "contratos",
    subarea: "Elaboração de contrato",
    case_type: "Contrato de prestação de serviços",
    case_summary:
      "Profissional autônomo deseja elaborar contrato-padrão para seus clientes. Não possui minuta. Sem conflito atual.",
    urgency: "baixa",
    urgency_reason: "Demanda preventiva",
    commercial_status: "cliente_ativo",
    legal_status: "em_elaboracao",
    financial_status: "quitado",
    source: "whatsapp",
    assigned_to: "u2",
    consent_given: true,
    consent_at: "2026-05-20T16:00:00Z",
    privacy_policy_version: "1.0.0",
    process_number: null,
    has_existing_process: false,
    is_existing_client: true,
    preferred_contact_time: "Comercial",
    next_action: "Entregar minuta para revisão",
    created_at: "2026-05-20T15:50:00Z",
    updated_at: "2026-05-28T14:20:00Z",
  },
];

export const mockTimeline: Record<string, TimelineEntry[]> = {
  "lead-001": [
    {
      id: "t1",
      lead_id: "lead-001",
      type: "message",
      title: "Atendimento iniciado pelo chatbot",
      description: "Triagem inicial — área Penal identificada, urgência ALTA.",
      author: "Assistente virtual",
      created_at: "2026-05-30T03:18:00Z",
    },
    {
      id: "t2",
      lead_id: "lead-001",
      type: "status_change",
      title: "Marcado como prioritário",
      description: "Handoff automático para equipe jurídica.",
      author: "Sistema",
      created_at: "2026-05-30T03:25:00Z",
    },
    {
      id: "t3",
      lead_id: "lead-001",
      type: "note",
      title: "Contato telefônico realizado",
      description: "Confirmados dados da audiência de custódia.",
      author: "Dr. Jean Braz",
      created_at: "2026-05-30T05:40:00Z",
    },
  ],
};

export const mockDocuments: Record<string, LegalDocument[]> = {
  "lead-005": [
    {
      id: "d1",
      lead_id: "lead-005",
      client_id: null,
      case_id: null,
      process_id: null,
      file_name: "contrato_financiamento.pdf",
      file_type: "application/pdf",
      file_size: 248000,
      storage_path: "leads/lead-005/contrato_financiamento.pdf",
      category: "contrato",
      uploaded_by: "lead-005",
      review_status: "revisado",
      created_at: "2026-05-25T16:00:00Z",
    },
    {
      id: "d2",
      lead_id: "lead-005",
      client_id: null,
      case_id: null,
      process_id: null,
      file_name: "extratos_banco.pdf",
      file_type: "application/pdf",
      file_size: 512000,
      storage_path: "leads/lead-005/extratos_banco.pdf",
      category: "comprovante",
      uploaded_by: "lead-005",
      review_status: "pendente",
      created_at: "2026-05-26T09:30:00Z",
    },
  ],
};

export const mockTasks: Task[] = [
  {
    id: "task-1",
    lead_id: "lead-001",
    client_id: null,
    case_id: null,
    process_id: null,
    title: "Comparecer à audiência de custódia",
    description: "Audiência de custódia — Foro Central.",
    assigned_to: "u1",
    due_date: "2026-05-30T13:00:00Z",
    priority: "alta",
    status: "em_andamento",
    created_at: "2026-05-30T03:30:00Z",
    updated_at: "2026-05-30T03:30:00Z",
  },
  {
    id: "task-2",
    lead_id: "lead-003",
    client_id: null,
    case_id: null,
    process_id: null,
    title: "Protocolar defesa no PAD",
    description: "Prazo de defesa administrativa.",
    assigned_to: "u2",
    due_date: "2026-06-05T18:00:00Z",
    priority: "alta",
    status: "pendente",
    created_at: "2026-05-27T09:10:00Z",
    updated_at: "2026-05-27T09:10:00Z",
  },
  {
    id: "task-3",
    lead_id: "lead-002",
    client_id: null,
    case_id: null,
    process_id: null,
    title: "Analisar contrato e comprovantes",
    description: null,
    assigned_to: "u2",
    due_date: "2026-06-02T18:00:00Z",
    priority: "media",
    status: "pendente",
    created_at: "2026-05-29T10:35:00Z",
    updated_at: "2026-05-29T10:35:00Z",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "appt-1",
    lead_id: "lead-003",
    client_id: null,
    assigned_to: "u2",
    title: "Reunião de estratégia — PAD",
    date: "2026-06-01",
    start_time: "10:00",
    end_time: "11:00",
    modality: "online",
    meeting_link: "https://meet.example.com/braz-pad",
    status: "agendada",
    notes: "Definir linha de defesa.",
    created_at: "2026-05-29T16:05:00Z",
  },
  {
    id: "appt-2",
    lead_id: "lead-005",
    client_id: null,
    assigned_to: "u1",
    title: "Assinatura de contrato de honorários",
    date: "2026-06-02",
    start_time: "14:00",
    end_time: "14:30",
    modality: "presencial",
    meeting_link: null,
    status: "agendada",
    notes: null,
    created_at: "2026-05-29T19:15:00Z",
  },
];

export const mockFollowUps: FollowUp[] = [
  {
    id: "fu-1",
    lead_id: "lead-007",
    client_id: null,
    title: "Follow-up proposta LGPD",
    description: "Verificar retorno sobre a proposta de adequação.",
    scheduled_at: "2026-06-03T15:00:00Z",
    status: "pendente",
    assigned_to: "u2",
    created_at: "2026-05-27T11:05:00Z",
  },
  {
    id: "fu-2",
    lead_id: "lead-004",
    client_id: null,
    title: "Cobrar envio do CNIS",
    description: "Cliente ainda não enviou CNIS e carteira de trabalho.",
    scheduled_at: "2026-06-01T10:00:00Z",
    status: "pendente",
    assigned_to: "u2",
    created_at: "2026-05-28T09:05:00Z",
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: "n1",
    user_id: "u1",
    type: "lead_urgente",
    title: "Lead urgente — Penal (flagrante)",
    body: "Carlos Henrique Souza: audiência de custódia em menos de 24h.",
    read: false,
    entity_type: "lead",
    entity_id: "lead-001",
    created_at: "2026-05-30T03:25:00Z",
  },
  {
    id: "n2",
    user_id: "u2",
    type: "tarefa_vencendo",
    title: "Tarefa próxima do prazo",
    body: "Protocolar defesa no PAD — vence em 05/06.",
    read: false,
    entity_type: "task",
    entity_id: "task-2",
    created_at: "2026-05-30T08:00:00Z",
  },
  {
    id: "n3",
    user_id: "u2",
    type: "documento_enviado",
    title: "Novo documento enviado",
    body: "Roberto Carlos Menezes enviou extratos bancários.",
    read: false,
    entity_type: "lead",
    entity_id: "lead-005",
    created_at: "2026-05-26T09:31:00Z",
  },
  {
    id: "n4",
    user_id: "u2",
    type: "follow_up_pendente",
    title: "Follow-up pendente",
    body: "Cobrar envio do CNIS — Maria Aparecida Gomes.",
    read: true,
    entity_type: "lead",
    entity_id: "lead-004",
    created_at: "2026-05-28T09:05:00Z",
  },
  {
    id: "n5",
    user_id: "u1",
    type: "novo_lead",
    title: "Novo lead recebido",
    body: "Ana Beatriz Rocha — Regularização Imobiliária (usucapião).",
    read: true,
    entity_type: "lead",
    entity_id: "lead-006",
    created_at: "2026-05-24T09:55:00Z",
  },
];

export function getLeadById(id: string): Lead | undefined {
  return mockLeads.find((l) => l.id === id);
}

export function getUserName(id: string | null): string {
  if (!id) return "Sem responsável";
  return mockTeam.find((u) => u.id === id)?.name ?? "—";
}
